In [1]:
import pandas as pd

In [2]:
hotel_2301 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2301.CSV'
hotel_2302 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2302.CSV'
hotel_2303 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2303.CSV'
hotel_2304 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2304.CSV'
hotel_2305 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2305.CSV'
hotel_2306 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2306.CSV'
hotel_2307 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2307.CSV'
hotel_2308 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2308.CSV'
hotel_2309 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2309.CSV'
hotel_2310 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2310.CSV'
hotel_2311 = 'Data/HOTEL_2023_01to11/Hotel_data2023/HOT2311.CSV'


file_paths_2023 = [hotel_2301, hotel_2302, hotel_2303, hotel_2304,\
              hotel_2305, hotel_2306, hotel_2307, hotel_2308,\
              hotel_2309, hotel_2310, hotel_2311]
# append data from Jan 2023 to Nov 2023
dfs = []


headers = [
    "Taxpayer_Number", "Taxpayer_Name", "Taxpayer_Address", "Taxpayer_City", "Taxpayer_State",
    "Taxpayer_Zip", "Taxpayer_County", "Taxpayer_Phone", "Location_Number", "Location_Name",
    "Location_Address", "Location_City", "Location_State", "Location_Zip", "Location_County",
    "Location_Phone", "Unit_Capacity", "Responsibility_Begin_Date_(YYYYMMDD)",
    "Responsibility_End_Date_(YYYYMMDD)", "Obligation_End_Date_(YYYYMMDD)", "Filer_Type",
    "Total_Room_Receipts", "Taxable_Receipts"
]


for file in file_paths_2023:
    try:
        df = pd.read_csv(file, names=headers, header=None, encoding='ISO-8859-1')  # or 'latin1' or 'windows-1252'
        dfs.append(df)
    except UnicodeDecodeError as e:
        print(f"Error reading {file}: {e}")

hotel_2023 = pd.concat(dfs, ignore_index=True)

In [3]:
# hotel_2017_path = 'Data/HOTEL2017/HOTEL2017.CSV'
# hotel_2018_path = 'Data/HOTEL2018/HOTEL18.CSV'
# hotel_2019_path = 'Data/HOTEL2019/HOTEL2019.CSV'
# hotel_2020_path = 'Data/HOTEL2020/HOTEL2020.CSV'
hotel_2021_path = 'Data/HOTEL2021/HOTEL2021.CSV'
hotel_2022_path = 'Data/HOTEL2022/HOTEL2022.CSV'

In [4]:
hotel_2023.dtypes

Taxpayer_Number                           int64
Taxpayer_Name                            object
Taxpayer_Address                         object
Taxpayer_City                            object
Taxpayer_State                           object
Taxpayer_Zip                             object
Taxpayer_County                           int64
Taxpayer_Phone                           object
Location_Number                           int64
Location_Name                            object
Location_Address                         object
Location_City                            object
Location_State                           object
Location_Zip                              int64
Location_County                          object
Location_Phone                           object
Unit_Capacity                             int64
Responsibility_Begin_Date_(YYYYMMDD)      int64
Responsibility_End_Date_(YYYYMMDD)       object
Obligation_End_Date_(YYYYMMDD)            int64
Filer_Type                                int64
Total_Room_Receipts                     float64
Taxable_Receipts                        float64
dtype: object

In [5]:
# similar structure to append data from 2017 to 2022
# file_path_17_to_22= [hotel_2017_path, hotel_2018_path, hotel_2019_path,\
#                     hotel_2020_path, hotel_2021_path, hotel_2022_path]

# Updated has 2021 to 2023 
file_path_17_to_22= [hotel_2021_path, hotel_2022_path]


# Data type specification for zip codes as strings
dtype_spec = {'Taxpayer_Zip': str, 'Location_Zip': str}

# Function to clean zip codes
def clean_zip_code(zip_code):
    clean_zip = ''.join(filter(str.isdigit, str(zip_code)))
    return clean_zip[:5] if len(clean_zip) >= 5 else None



df1s = []

for file in file_path_17_to_22:
    try:
        # Adding low_memory=False parameter
        df = pd.read_csv(file, names=headers, header=None, encoding='ISO-8859-1', dtype=dtype_spec, low_memory=False)
        # Clean Location_Zip
        df['Location_Zip'] = df['Location_Zip'].apply(clean_zip_code)
        df = df[df['Location_Zip'].str.isnumeric()]  # Filter only numeric zips
        df1s.append(df)
    except UnicodeDecodeError as e:
        print(f"Error reading {file}: {e}")

hotel_17_to_22 = pd.concat(df1s, ignore_index=True)

In [6]:
hotel_17_to_22

,Taxpayer_Number,Taxpayer_Name,Taxpayer_Address,Taxpayer_City,Taxpayer_State,Taxpayer_Zip,Taxpayer_County,Taxpayer_Phone,Location_Number,Location_Name,...,Location_Zip,Location_County,Location_Phone,Unit_Capacity,Responsibility_Begin_Date_(YYYYMMDD),Responsibility_End_Date_(YYYYMMDD),Obligation_End_Date_(YYYYMMDD),Filer_Type,Total_Room_Receipts,Taxable_Receipts
0,10105515737,"TAN 1 ON, INC. ...",8504 LANDING WAY CT,FORT WORTH,TX,76179,220,8174754668,6,LAKEVIEW MARINA ...,...,76179,220,,2,20200301,,20210331,60,100.00,100.00
1,10105515737,"TAN 1 ON, INC. ...",8504 LANDING WAY CT,FORT WORTH,TX,76179,220,8174754668,6,LAKEVIEW MARINA ...,...,76179,220,,2,20200301,,20210630,60,6173.50,6173.50
2,10105515737,"TAN 1 ON, INC. ...",8504 LANDING WAY CT,FORT WORTH,TX,76179,220,8174754668,6,LAKEVIEW MARINA ...,...,76179,220,,2,20200301,,20210930,60,6825.00,6825.00
3,10105515737,"TAN 1 ON, INC. ...",8504 LANDING WAY CT,FORT WORTH,TX,76179,220,8174754668,6,LAKEVIEW MARINA ...,...,76179,220,,2,20200301,,20211231,60,1320.00,1320.00
4,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210131,50,97709.97,97709.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449688,39000015964,BENNIE L MCGRIFF ...,1011 PARVIEW CIR,CEDAR HILL,TX,75104,57,2147281677,5,MAC'S DINER & MOTEL ...,...,75144,175,9033967507,17,20060601,,20220831,50,0.00,0.00
449689,39000015964,BENNIE L MCGRIFF ...,1011 PARVIEW CIR,CEDAR HILL,TX,75104,57,2147281677,5,MAC'S DINER & MOTEL ...,...,75144,175,9033967507,17,20060601,,20220930,50,360.00,360.00
449690,39000015964,BENNIE L MCGRIFF ...,1011 PARVIEW CIR,CEDAR HILL,TX,75104,57,2147281677,5,MAC'S DINER & MOTEL ...,...,75144,175,9033967507,17,20060601,,20221031,50,180.00,180.00
449691,39000015964,BENNIE L MCGRIFF ...,1011 PARVIEW CIR,CEDAR HILL,TX,75104,57,2147281677,5,MAC'S DINER & MOTEL ...,...,75144,175,9033967507,17,20060601,,20221130,50,200.00,200.00
449692,39000015964,BENNIE L MCGRIFF ...,1011 PARVIEW CIR,CEDAR HILL,TX,75104,57,2147281677,5,MAC'S DINER & MOTEL ...,...,75144,175,9033967507,17,20060601,,20221231,50,135.00,135.00

In [7]:
hotel_17_to_22.dtypes

Taxpayer_Number                           int64
Taxpayer_Name                            object
Taxpayer_Address                         object
Taxpayer_City                            object
Taxpayer_State                           object
Taxpayer_Zip                             object
Taxpayer_County                           int64
Taxpayer_Phone                           object
Location_Number                           int64
Location_Name                            object
Location_Address                         object
Location_City                            object
Location_State                           object
Location_Zip                             object
Location_County                          object
Location_Phone                           object
Unit_Capacity                             int64
Responsibility_Begin_Date_(YYYYMMDD)      int64
Responsibility_End_Date_(YYYYMMDD)       object
Obligation_End_Date_(YYYYMMDD)            int64
Filer_Type                                int64
Total_Room_Receipts                     float64
Taxable_Receipts                        float64
dtype: object

In [8]:
hotel_17_to_Nov23 = pd.concat([hotel_17_to_22, hotel_2023], ignore_index=True)

In [9]:
hotel_17_to_Nov23

,Taxpayer_Number,Taxpayer_Name,Taxpayer_Address,Taxpayer_City,Taxpayer_State,Taxpayer_Zip,Taxpayer_County,Taxpayer_Phone,Location_Number,Location_Name,...,Location_Zip,Location_County,Location_Phone,Unit_Capacity,Responsibility_Begin_Date_(YYYYMMDD),Responsibility_End_Date_(YYYYMMDD),Obligation_End_Date_(YYYYMMDD),Filer_Type,Total_Room_Receipts,Taxable_Receipts
0,10105515737,"TAN 1 ON, INC. ...",8504 LANDING WAY CT,FORT WORTH,TX,76179,220,8174754668,6,LAKEVIEW MARINA ...,...,76179,220,,2,20200301,,20210331,60,100.00,100.00
1,10105515737,"TAN 1 ON, INC. ...",8504 LANDING WAY CT,FORT WORTH,TX,76179,220,8174754668,6,LAKEVIEW MARINA ...,...,76179,220,,2,20200301,,20210630,60,6173.50,6173.50
2,10105515737,"TAN 1 ON, INC. ...",8504 LANDING WAY CT,FORT WORTH,TX,76179,220,8174754668,6,LAKEVIEW MARINA ...,...,76179,220,,2,20200301,,20210930,60,6825.00,6825.00
3,10105515737,"TAN 1 ON, INC. ...",8504 LANDING WAY CT,FORT WORTH,TX,76179,220,8174754668,6,LAKEVIEW MARINA ...,...,76179,220,,2,20200301,,20211231,60,1320.00,1320.00
4,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210131,50,97709.97,97709.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669110,32092303232,"KRISHNA HOTELS, L.L.C. ...",500 S BOYD ST,ABERDEEN,SD,57401,0,6052263163,1,HOLIDAY EXPRESS ...,...,79015,191,,66,20231024,,20231130,50,106034.62,94777.92
669111,32092526568,WISE HOSPITALITY LLC CA ENTITY ...,12924 CHARLWOOD ST,CERRITOS,CA,90703,0,5625999511,1,HOLIDAY INN EXPRESS ...,...,78520,031,9565500666,74,20231117,,20231130,50,91302.83,91302.83
669112,32092828311,JYS2017 TRUST NO 2 ...,PO BOX 3089,GREENWOOD VILLAGE,CO,80155,0,3032200183,1,125 BUD LANE ...,...,78639,027,,1,20230901,,20231130,50,10024.88,10024.88
669113,39000012896,MARIA RIVERA ...,820 S CLOSNER BLVD APT 9,EDINBURG,TX,78539,108,9564097474,8,CASA MANANA MOTEL ...,...,78539,108,,15,20100524,,20231130,50,2725.45,2725.45
669114,39000015964,BENNIE L MCGRIFF ...,1011 PARVIEW CIR,CEDAR HILL,TX,75104,57,2147281677,5,MAC'S DINER & MOTEL ...,...,75144,175,9033967507,17,20060601,,20231130,50,140.00,140.00

In [10]:
Dallas = hotel_17_to_Nov23[hotel_17_to_Nov23['Location_City'].str.contains('DALLAS')]

In [17]:
Dallas

,Taxpayer_Number,Taxpayer_Name,Taxpayer_Address,Taxpayer_City,Taxpayer_State,Taxpayer_Zip,Taxpayer_County,Taxpayer_Phone,Location_Number,Location_Name,...,Location_Zip,Location_County,Location_Phone,Unit_Capacity,Responsibility_Begin_Date_(YYYYMMDD),Responsibility_End_Date_(YYYYMMDD),Obligation_End_Date_(YYYYMMDD),Filer_Type,Total_Room_Receipts,Taxable_Receipts
4,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210131,50,97709.97,97709.97
5,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210228,50,86274.08,86274.08
6,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210331,50,116618.01,116618.01
7,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210430,50,113138.11,113138.11
8,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210531,50,115246.34,115246.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669025,32090249320,KRUPALU DEV LLC ...,1736 FORT WORTH AVE,DALLAS,TX,75208,57,4697894454,1,MOTEL 6 ...,...,75208,057,,40,20230701,,20231130,50,50490.00,50490.00
669027,32090283154,LAKSHMI NARAYAN LLC ...,3511 E KIEST BLVD,DALLAS,TX,75203,57,2148921323,1,ALL SEASONS INN AND SUITES ...,...,75203,057,,33,20230701,,20231130,50,12365.00,10752.17
669046,32090718696,INDEPENDENT HOTEL LLC ...,4220 INDEPENDENCE DR,DALLAS,TX,75237,57,3618164210,1,SUPER 7 ...,...,75237,057,,128,20230901,,20231130,50,105716.50,58074.21
669066,32091063589,SW HOTELS LLC ...,255 MARY ANN DR,JACKSONVILLE,OR,97530,0,6617697104,1,HOLIDAY INN EXPRESS & SUITES DALLAS EAST- FAIR...,...,75228,057,,90,20231030,,20231130,50,147765.35,132436.87
669097,32091571714,CREP DALLAS HOTEL OPCO LLC ...,4500 HARRY HINES BLVD,DALLAS,TX,75219,57,2028351000,1,HOLIDAY INN DALLAS MARKET CENTER ...,...,75219,057,,200,20231107,,20231130,50,160295.41,147165.05

In [29]:
# Keep filtering hotel which still are in the market, delete the ones which has value in Responsibility_End_Date
# Filter the DataFrame to keep only rows where the 'Responsibility End Date (YYYYMMDD)' column is an empty string after stripping white spaces
Dallas_active_hotels = Dallas[Dallas['Responsibility_End_Date_(YYYYMMDD)'].str.strip() == '']

# Display the first few rows of the filtered DataFrame to verify the result
Dallas_active_hotels

,Taxpayer_Number,Taxpayer_Name,Taxpayer_Address,Taxpayer_City,Taxpayer_State,Taxpayer_Zip,Taxpayer_County,Taxpayer_Phone,Location_Number,Location_Name,...,Location_Zip,Location_County,Location_Phone,Unit_Capacity,Responsibility_Begin_Date_(YYYYMMDD),Responsibility_End_Date_(YYYYMMDD),Obligation_End_Date_(YYYYMMDD),Filer_Type,Total_Room_Receipts,Taxable_Receipts
4,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210131,50,97709.97,97709.97
5,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210228,50,86274.08,86274.08
6,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210331,50,116618.01,116618.01
7,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210430,50,113138.11,113138.11
8,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,75224,057,,80,20100222,,20210531,50,115246.34,115246.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669025,32090249320,KRUPALU DEV LLC ...,1736 FORT WORTH AVE,DALLAS,TX,75208,57,4697894454,1,MOTEL 6 ...,...,75208,057,,40,20230701,,20231130,50,50490.00,50490.00
669027,32090283154,LAKSHMI NARAYAN LLC ...,3511 E KIEST BLVD,DALLAS,TX,75203,57,2148921323,1,ALL SEASONS INN AND SUITES ...,...,75203,057,,33,20230701,,20231130,50,12365.00,10752.17
669046,32090718696,INDEPENDENT HOTEL LLC ...,4220 INDEPENDENCE DR,DALLAS,TX,75237,57,3618164210,1,SUPER 7 ...,...,75237,057,,128,20230901,,20231130,50,105716.50,58074.21
669066,32091063589,SW HOTELS LLC ...,255 MARY ANN DR,JACKSONVILLE,OR,97530,0,6617697104,1,HOLIDAY INN EXPRESS & SUITES DALLAS EAST- FAIR...,...,75228,057,,90,20231030,,20231130,50,147765.35,132436.87
669097,32091571714,CREP DALLAS HOTEL OPCO LLC ...,4500 HARRY HINES BLVD,DALLAS,TX,75219,57,2028351000,1,HOLIDAY INN DALLAS MARKET CENTER ...,...,75219,057,,200,20231107,,20231130,50,160295.41,147165.05

In [30]:
Dallas = Dallas_active_hotels

In [31]:
unique_payer = len(set(Dallas['Taxpayer_Number']))
unique_payer

419

In [32]:
unique_taxpayer = len(set(Dallas['Taxpayer_Number']))
print("Number of unique Taxpayer: ", unique_taxpayer)

Number of unique Taxpayer:  419

In [34]:
import csv
Dallas.to_csv("Dallas.csv", index=False, header=False)

In [35]:
# Drop duplicate rows based on the specified columns
unique_locations = Dallas.drop_duplicates(subset=['Location_Number', 'Location_Name', 'Location_Address','Location_County'])

# Reset the index to ensure it starts from 0
unique_locations.reset_index(drop=True, inplace=True)

# Add a new column 'Location_ID' with incremental values starting from 1
unique_locations['Location_ID'] = range(1, len(unique_locations) + 1)

# Get the number of unique locations
num_unique_locations = unique_locations.shape[0]

print("Number of unique locations:", num_unique_locations)

Number of unique locations: 562

/var/folders/8m/8by7qkhx3n5fnnpb_stj_97m0000gn/T/ipykernel_16198/366523289.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_locations['Location_ID'] = range(1, len(unique_locations) + 1)

In [36]:
# Merge the original Dallas DataFrame with the unique_locations to include the Location_ID
Dallas_with_ID = Dallas.merge(unique_locations[['Location_Number', 'Location_Name', 'Location_Address', 'Location_County', 'Location_ID']], 
                              on=['Location_Number', 'Location_Name', 'Location_Address', 'Location_County'], 
                              how='left')

In [37]:
unique_ID = len(set(Dallas_with_ID['Location_ID']))
print("Number of unique Location_ID: ", unique_ID)

Number of unique Location_ID:  562

In [38]:
Dallas_with_ID

,Taxpayer_Number,Taxpayer_Name,Taxpayer_Address,Taxpayer_City,Taxpayer_State,Taxpayer_Zip,Taxpayer_County,Taxpayer_Phone,Location_Number,Location_Name,...,Location_County,Location_Phone,Unit_Capacity,Responsibility_Begin_Date_(YYYYMMDD),Responsibility_End_Date_(YYYYMMDD),Obligation_End_Date_(YYYYMMDD),Filer_Type,Total_Room_Receipts,Taxable_Receipts,Location_ID
0,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210131,50,97709.97,97709.97,1
1,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210228,50,86274.08,86274.08,1
2,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210331,50,116618.01,116618.01,1
3,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210430,50,113138.11,113138.11,1
4,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210531,50,115246.34,115246.34,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,32090249320,KRUPALU DEV LLC ...,1736 FORT WORTH AVE,DALLAS,TX,75208,57,4697894454,1,MOTEL 6 ...,...,057,,40,20230701,,20231130,50,50490.00,50490.00,555
12344,32090283154,LAKSHMI NARAYAN LLC ...,3511 E KIEST BLVD,DALLAS,TX,75203,57,2148921323,1,ALL SEASONS INN AND SUITES ...,...,057,,33,20230701,,20231130,50,12365.00,10752.17,549
12345,32090718696,INDEPENDENT HOTEL LLC ...,4220 INDEPENDENCE DR,DALLAS,TX,75237,57,3618164210,1,SUPER 7 ...,...,057,,128,20230901,,20231130,50,105716.50,58074.21,556
12346,32091063589,SW HOTELS LLC ...,255 MARY ANN DR,JACKSONVILLE,OR,97530,0,6617697104,1,HOLIDAY INN EXPRESS & SUITES DALLAS EAST- FAIR...,...,057,,90,20231030,,20231130,50,147765.35,132436.87,560
12347,32091571714,CREP DALLAS HOTEL OPCO LLC ...,4500 HARRY HINES BLVD,DALLAS,TX,75219,57,2028351000,1,HOLIDAY INN DALLAS MARKET CENTER ...,...,057,,200,20231107,,20231130,50,160295.41,147165.05,248

In [39]:
# Find rows where Location_ID is missing
# Check for the case if multiple hotels are at the same location
hotels_without_id = Dallas_with_ID[Dallas_with_ID['Location_ID'].isna()]
# Check if there are any such hotels
if not hotels_without_id.empty:
    print("These hotels have no ID")
    # Optionally, you can print these rows to examine them
    print(hotels_without_id)
else:
    print("Every hotel has an ID.")

Every hotel has an ID.

In [42]:
Dallas_with_ID_sorted = Dallas_with_ID.sort_values(by=['Location_ID', 'Obligation_End_Date_(YYYYMMDD)'])
Dallas_with_ID_sorted.head(30)

,Taxpayer_Number,Taxpayer_Name,Taxpayer_Address,Taxpayer_City,Taxpayer_State,Taxpayer_Zip,Taxpayer_County,Taxpayer_Phone,Location_Number,Location_Name,...,Location_County,Location_Phone,Unit_Capacity,Responsibility_Begin_Date_(YYYYMMDD),Responsibility_End_Date_(YYYYMMDD),Obligation_End_Date_(YYYYMMDD),Filer_Type,Total_Room_Receipts,Taxable_Receipts,Location_ID
0,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210131,50,97709.97,97709.97,1
1,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210228,50,86274.08,86274.08,1
2,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210331,50,116618.01,116618.01,1
3,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210430,50,113138.11,113138.11,1
4,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210531,50,115246.34,115246.34,1
5,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210630,50,104191.35,104191.35,1
6,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210731,50,119418.26,119418.26,1
7,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210831,50,96114.58,96114.58,1
8,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20210930,50,91479.71,91479.71,1
9,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20211031,50,107150.37,107150.37,1
10,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20211130,50,90597.71,90597.71,1
11,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20211231,50,93138.19,93138.19,1
3485,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20220131,50,87278.98,87278.98,1
3486,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20220228,50,81508.42,81508.42,1
3487,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20220331,50,96534.56,96534.56,1
3488,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20220430,50,105661.66,105661.66,1
3489,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20220531,50,103091.01,103091.01,1
3490,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20220630,50,105310.20,105310.20,1
3491,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20220731,50,109607.69,109607.69,1
3492,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20220831,50,97915.33,97915.33,1
3493,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20220930,50,103359.99,103359.99,1
3494,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20221031,50,106828.47,106828.47,1
3495,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20221130,50,98716.44,98716.44,1
3496,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20221231,50,106098.76,106098.76,1
7940,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20230131,50,92907.99,92907.99,1
8327,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20230228,50,91995.16,91995.16,1
8713,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20230331,50,103634.09,103634.09,1
9235,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20230430,50,118655.42,118655.42,1
9625,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20230531,50,115578.13,115578.13,1
9962,10105603723,"OAK CLIFF HOSPITALITY, L.P. ...",4610 S R L THORNTON FWY,DALLAS,TX,75224,57,2143716800,2,DELUXINN ...,...,057,,80,20100222,,20230630,50,113206.33,113206.33,1

In [43]:
Dallas_with_ID_sorted.to_csv("Dallas_with_ID.csv",index=False, header=False)